import { Sidebar } from './components/Sidebar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ display: 'grid', gridTemplateColumns: 'auto 1fr' }}>
        <aside>
          <Sidebar />
        </aside>
        <main style={{ padding: '6rem 0' }}>{children}</main>
      </body>
    </html>
  )
}
